name: olivia-test
version: '1.0'
summary: Elegant Cloud Music Player for Linux Desktop
description: |
  Olivia is a online/offline cloud based music player like iTunes, Spotify etc,Olivia allows you to search any music online stream it, you can set player to cache your streams while playback. Olivia lets you create and manage your music library.
grade: stable
confinement: strict
icon: snap/gui/icon.png

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  olivia:
    command: desktop-launch olivia
    environment:
       QT_STYLE_OVERRIDE: "gtk"
       DISABLE_WAYLAND: 1
    desktop: usr/share/applications/olivia.desktop
    plugs:
        - home
        - unity7
        - browser-support
        - network
        - network-bind
        - opengl
        - pulseaudio
        - x11
        - alsa
        - desktop
        - network-manager
        - gsettings
        - process-control
        - desktop-legacy
        - dbus

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

parts:
   deps:
     plugin: nil
     stage-packages:
            - socat
            - python
            - wget
            - coreutils
   ppa:
     plugin: nil
     override-pull: |
       apt install wget
       echo "deb http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu xenial main" >>  /etc/apt/sources.list
       wget -qO - http://ktechpit.com/USS/Olivia/snapcraft/mpv.key | apt-key add -
       apt update
   mpv:
     plugin: nil
     after: [ppa,qt]
     stage-packages:
           - mpv
           - ffmpeg
   qt:
     plugin: qmake
     qt-version: qt5
     source-type: git
     source: https://github.com/keshavbhatt/olivia.git
     build-packages:
            - build-essential
            - qtbase5-dev
            - libqt5webkit5-dev
     stage:
          - -usr/share/pkgconfig
     stage-packages:
          - libqt5sql5-sqlite
          - libqt5webkit5
          - libqt5x11extras5
          - libqt5xml5
          - libdb5.3
     override-build: |
            snapcraftctl build
            sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/olivia.desktop
            cp -rf ${SNAPCRAFT_PART_SRC}/olivia.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/olivia.desktop
     after: [desktop-qt5]

   cleanup:
       after: 
            - qt
       plugin: nil
       override-prime: |
          # Remove unneeded stage files to save space
          cd usr/share
          rm -rf apport bash-completion bug doc doc-base icons lintian man pam-configs pkgconfig themes upstart zsh
